# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tplan.ui'
#
# Created: Fri May 08 11:50:39 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.boardComboBox = QtGui.QComboBox(self.centralwidget)
        self.boardComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boardComboBox.setObjectName("boardComboBox")
        self.boardComboBox.addItem("")
        self.boardComboBox.addItem("")
        self.boardComboBox.addItem("")
        self.boardComboBox.addItem("")
        self.boardComboBox.addItem("")
        self.verticalLayout_5.addWidget(self.boardComboBox)
        self.autoButton = QtGui.QPushButton(self.centralwidget)
        self.autoButton.setObjectName("autoButton")
        self.verticalLayout_5.addWidget(self.autoButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectButton1 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton1.sizePolicy().hasHeightForWidth())
        self.selectButton1.setSizePolicy(sizePolicy)
        self.selectButton1.setMaximumSize(QtCore.QSize(32, 16777215))
        self.selectButton1.setStyleSheet("")
        self.selectButton1.setCheckable(True)
        self.selectButton1.setChecked(False)
        self.selectButton1.setObjectName("selectButton1")
        self.horizontalLayout_2.addWidget(self.selectButton1)
        self.selectButton2 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton2.sizePolicy().hasHeightForWidth())
        self.selectButton2.setSizePolicy(sizePolicy)
        self.selectButton2.setMaximumSize(QtCore.QSize(32, 16777215))
        self.selectButton2.setCheckable(True)
        self.selectButton2.setChecked(False)
        self.selectButton2.setObjectName("selectButton2")
        self.horizontalLayout_2.addWidget(self.selectButton2)
        self.selectButton3 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton3.sizePolicy().hasHeightForWidth())
        self.selectButton3.setSizePolicy(sizePolicy)
        self.selectButton3.setMaximumSize(QtCore.QSize(32, 16777215))
        self.selectButton3.setCheckable(True)
        self.selectButton3.setChecked(False)
        self.selectButton3.setObjectName("selectButton3")
        self.horizontalLayout_2.addWidget(self.selectButton3)
        self.selectButton4 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton4.sizePolicy().hasHeightForWidth())
        self.selectButton4.setSizePolicy(sizePolicy)
        self.selectButton4.setMaximumSize(QtCore.QSize(32, 16777215))
        self.selectButton4.setCheckable(True)
        self.selectButton4.setChecked(False)
        self.selectButton4.setObjectName("selectButton4")
        self.horizontalLayout_2.addWidget(self.selectButton4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.manualGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.manualGroupBox.setEnabled(True)
        self.manualGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.manualGroupBox.setObjectName("manualGroupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.manualGroupBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.interfaceButton = QtGui.QPushButton(self.manualGroupBox)
        self.interfaceButton.setObjectName("interfaceButton")
        self.verticalLayout_3.addWidget(self.interfaceButton)
        self.bootloaderButton = QtGui.QPushButton(self.manualGroupBox)
        self.bootloaderButton.setObjectName("bootloaderButton")
        self.verticalLayout_3.addWidget(self.bootloaderButton)
        self.programButton = QtGui.QPushButton(self.manualGroupBox)
        self.programButton.setObjectName("programButton")
        self.verticalLayout_3.addWidget(self.programButton)
        self.testButton = QtGui.QPushButton(self.manualGroupBox)
        self.testButton.setObjectName("testButton")
        self.verticalLayout_3.addWidget(self.testButton)
        self.resetButton = QtGui.QPushButton(self.manualGroupBox)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_3.addWidget(self.resetButton)
        self.verticalLayout_5.addWidget(self.manualGroupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.clearButton = QtGui.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout_5.addWidget(self.clearButton)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.logTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setObjectName("logTextEdit")
        self.horizontalLayout.addWidget(self.logTextEdit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.bootloaderButton, self.programButton)
        MainWindow.setTabOrder(self.programButton, self.testButton)
        MainWindow.setTabOrder(self.testButton, self.logTextEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "TPlan for Arduino Form-factor Board", None, QtGui.QApplication.UnicodeUTF8))
        self.boardComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Seeeduino", None, QtGui.QApplication.UnicodeUTF8))
        self.boardComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Seeeduino Lotus", None, QtGui.QApplication.UnicodeUTF8))
        self.boardComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Seeeduino Lite", None, QtGui.QApplication.UnicodeUTF8))
        self.boardComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Arch", None, QtGui.QApplication.UnicodeUTF8))
        self.boardComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Arch BLE", None, QtGui.QApplication.UnicodeUTF8))
        self.autoButton.setText(QtGui.QApplication.translate("MainWindow", "Auto Test", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.manualGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Manual Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.interfaceButton.setText(QtGui.QApplication.translate("MainWindow", "Write Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.bootloaderButton.setText(QtGui.QApplication.translate("MainWindow", "Write Bootloader", None, QtGui.QApplication.UnicodeUTF8))
        self.programButton.setText(QtGui.QApplication.translate("MainWindow", "Write Test Program", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setText(QtGui.QApplication.translate("MainWindow", "Test Target", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "Write Product Program", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear Log", None, QtGui.QApplication.UnicodeUTF8))
        self.logTextEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

