# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tplan.ui'
#
# Created: Wed Mar 11 19:14:16 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.boardComboBox = QtGui.QComboBox(self.groupBox_3)
        self.boardComboBox.setObjectName("boardComboBox")
        self.boardComboBox.addItem("")
        self.boardComboBox.addItem("")
        self.verticalLayout_4.addWidget(self.boardComboBox)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.autoModeGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.autoModeGroupBox.setObjectName("autoModeGroupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.autoModeGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.autoButton = QtGui.QPushButton(self.autoModeGroupBox)
        self.autoButton.setObjectName("autoButton")
        self.verticalLayout_2.addWidget(self.autoButton)
        self.verticalLayout_5.addWidget(self.autoModeGroupBox)
        self.manualModeGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.manualModeGroupBox.setEnabled(True)
        self.manualModeGroupBox.setObjectName("manualModeGroupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.manualModeGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtGui.QLabel(self.manualModeGroupBox)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectButton1 = QtGui.QPushButton(self.manualModeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton1.sizePolicy().hasHeightForWidth())
        self.selectButton1.setSizePolicy(sizePolicy)
        self.selectButton1.setMaximumSize(QtCore.QSize(32, 16777215))
        self.selectButton1.setCheckable(True)
        self.selectButton1.setChecked(False)
        self.selectButton1.setObjectName("selectButton1")
        self.horizontalLayout_2.addWidget(self.selectButton1)
        self.selectButton2 = QtGui.QPushButton(self.manualModeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton2.sizePolicy().hasHeightForWidth())
        self.selectButton2.setSizePolicy(sizePolicy)
        self.selectButton2.setMaximumSize(QtCore.QSize(32, 16777215))
        self.selectButton2.setCheckable(True)
        self.selectButton2.setChecked(False)
        self.selectButton2.setObjectName("selectButton2")
        self.horizontalLayout_2.addWidget(self.selectButton2)
        self.selectButton3 = QtGui.QPushButton(self.manualModeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton3.sizePolicy().hasHeightForWidth())
        self.selectButton3.setSizePolicy(sizePolicy)
        self.selectButton3.setMaximumSize(QtCore.QSize(32, 16777215))
        self.selectButton3.setCheckable(True)
        self.selectButton3.setChecked(False)
        self.selectButton3.setObjectName("selectButton3")
        self.horizontalLayout_2.addWidget(self.selectButton3)
        self.selectButton4 = QtGui.QPushButton(self.manualModeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton4.sizePolicy().hasHeightForWidth())
        self.selectButton4.setSizePolicy(sizePolicy)
        self.selectButton4.setMaximumSize(QtCore.QSize(32, 16777215))
        self.selectButton4.setCheckable(True)
        self.selectButton4.setChecked(False)
        self.selectButton4.setObjectName("selectButton4")
        self.horizontalLayout_2.addWidget(self.selectButton4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.manualModeGroupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.interfaceButton = QtGui.QPushButton(self.manualModeGroupBox)
        self.interfaceButton.setObjectName("interfaceButton")
        self.verticalLayout_3.addWidget(self.interfaceButton)
        self.bootloaderButton = QtGui.QPushButton(self.manualModeGroupBox)
        self.bootloaderButton.setObjectName("bootloaderButton")
        self.verticalLayout_3.addWidget(self.bootloaderButton)
        self.programButton = QtGui.QPushButton(self.manualModeGroupBox)
        self.programButton.setObjectName("programButton")
        self.verticalLayout_3.addWidget(self.programButton)
        self.testButton = QtGui.QPushButton(self.manualModeGroupBox)
        self.testButton.setObjectName("testButton")
        self.verticalLayout_3.addWidget(self.testButton)
        self.resetButton = QtGui.QPushButton(self.manualModeGroupBox)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_3.addWidget(self.resetButton)
        self.verticalLayout_5.addWidget(self.manualModeGroupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.logTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setObjectName("logTextEdit")
        self.horizontalLayout.addWidget(self.logTextEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.autoButton, self.bootloaderButton)
        MainWindow.setTabOrder(self.bootloaderButton, self.programButton)
        MainWindow.setTabOrder(self.programButton, self.testButton)
        MainWindow.setTabOrder(self.testButton, self.logTextEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "TPlan for Arduino Form-factor Board", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Select Board Type", None, QtGui.QApplication.UnicodeUTF8))
        self.boardComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.boardComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Seeeduino V4", None, QtGui.QApplication.UnicodeUTF8))
        self.autoModeGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Auto Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.autoButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.manualModeGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Manual Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Board ID", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.interfaceButton.setText(QtGui.QApplication.translate("MainWindow", "Write Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.bootloaderButton.setText(QtGui.QApplication.translate("MainWindow", "Write Bootloader", None, QtGui.QApplication.UnicodeUTF8))
        self.programButton.setText(QtGui.QApplication.translate("MainWindow", "Write Program", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setText(QtGui.QApplication.translate("MainWindow", "Test Board", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset Board", None, QtGui.QApplication.UnicodeUTF8))
        self.logTextEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

